"""add account_name to balances

Revision ID: 41cc57bc1b3e
Revises: 572f480d25f4
Create Date: 2026-07-03 20:12:29.252115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cc57bc1b3e'
down_revision: Union[str, Sequence[str], None] = '572f480d25f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balances', schema=None) as batch_op:
        batch_op.drop_column('account_name')

    # ### end Alembic commands ###
