"""extending the transaction schema with debtor and creditor iban and bban numbers

Revision ID: be80fa44fa47
Revises: 41cc57bc1b3e
Create Date: 2026-09-06 00:42:48.628533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be80fa44fa47'
down_revision: Union[str, Sequence[str], None] = '41cc57bc1b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creditor_iban', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('creditor_bban', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('debtor_iban', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('debtor_bban', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('debtor_bban')
        batch_op.drop_column('debtor_iban')
        batch_op.drop_column('creditor_bban')
        batch_op.drop_column('creditor_iban')

    # ### end Alembic commands ###
